---
- hosts: "bo-credito"
  serial: 10
  remote_user: rreis

  tasks:
  - name: LInk
    file:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      owner: root
      group: root
      state: link
    with_items:
      - { src: '/media/cooperativas/0001/ArqTroca/ConsignacaoFolha/arquivosimportados/', dest: '/mnt/9012_ArquivosASCII' }
      - { src: '/media/arquivos-ArqTroca/ConsignacaoFolha/PROTOCOLOSARQRETORNO', dest: '/mnt/9013_Protocolo' }
      - { src: '/media/cooperativas/0001/ArqTroca/ConsignacaoFolha/BackupImportacao', dest: '/mnt/9014_BackupArquivoConvertido ' }
      - { src: '/media/arquivos-sistemas/INSS/DATAPREV/RECEBIDOS/subcsg12', dest: '/mnt/9015_Averbacao' }
      - { src: '/media/arquivos-sistemas/INSS/DATAPREV/RECEBIDOS/subeco11', dest: '/mnt/9016_Liquidacao' }
      - { src: '/media/arquivos-sistemas/INSS/DATAPREV/RECEBIDOS/subglo11', dest: '/mnt/9017_Glosas' }
      - { src: '/media/arquivos-sistemas/INSS/DATAPREV/RECEBIDOS/subcsg12/Backup', dest: '/mnt/9018_BackupArquivoOriginal' }
      - { src: '/media/arquivos-sistemas/INSS/DATAPREV/RECEBIDOS/subeco11/Backup', dest: '/mnt/9019_BackupArquivoOriginal' }
      - { src: '/media/arquivos-sistemas/INSS/DATAPREV/RECEBIDOS/subglo11/Backup', dest: '/mnt/9020_BackupArquivoOriginal' }
